### PR TITLE
Toto Lin's assignment for 7/12

### PR DESCRIPTION
**Pull request by lin-toto**

### CODE REVIEW

**Comment by JoeOsborn** [comment]
Day 1 looks good, though I'd like to see more discussion of metaphorical stance and the central/peripheral distinction (Agre's "critical technical practice" stuff) next time we do an explication.

I'll merge once I've had a chance to look at day 2.

**Comment by JoeOsborn** [comment]
Letters, `|`, and `*` would be a great foundation for a regex parser. It's possible to do `|` without NFAs, but if you wanted to build a "nondeterministic state machine" class you're welcome to try! It's more or less a state machine with a set of initial/current states instead of a single current state. You can also admit epsilon-transitions if you want to.

**Comment by lin-toto** [comment]
Thanks for reviewing my assignment! For the regex parser I'm just starting up to be simple and add more features step by step.

**Comment by lin-toto** [comment]
Thanks for the tips Professor! I got the switches to work

**Comment by JoeOsborn** [comment]
A couple remarks on your MCTS solver:
- `tree_policy` assumes that the outcome of a move is always the same, but this is not the case for e.g. pits. What you're doing is called _determinization_, and may lead to overly pessimistic or optimistic strategies. In other words, just because making a move from tree node `A` resulted in tree node `B` when we first expanded `A`, that doesn't mean making that move will always produce `B.maze` every time it's executed from `A.maze`.
- Second, you have different reward discounting in `default_policy` compared to `backup`. In `backup`, you have the correct exponential decay, but `default_policy` should return `reward*(gamma**move_count)`, and in your case it seems like gamma is 0.99.
- You may want to put a limit on how many moves you'll explore during `default_policy`; if it gets stuck in a cycle or wanders too much, that might explain your slow training.
- Finally, note that the `path` and `last_reward` you're returning are estimates at a leaf of the MCTS tree, not necessarily what you'll really get by running the maze.

The reinforcement learning agent looks pretty good! I think its performance may be improved using ideas from novelty search---give a reward for exploring maze configurations that haven't been seen before.

**Pull request closed without merging**
